CREATE DATABASE library;
USE library;
CREATE TABLE Book(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(30) UNIQUE,
    WRITER VARCHAR(30),
    PUBLISHER VARCHAR(30),
    PUBLISHED_YEAR INT
);