server:
 port: 8080
spring:
 mvc:
  view:
   prefix: /WEB-INF/pages/
   suffix: .jsp
 datasource:
  url: jdbc:mysql://localhost:3306/PARKING_Database
  username: root
  password: root
welcome :
   message : Welcome to Parking System 

